#### pandas数据结构

- series是一维的数据结构，可以直观理解为“一列”数据。它由索引index和values组成
- 构造series

1.通过列表构建:调用pd.Series()方法即可

In [1]:
import pandas as pd
import numpy as np

In [2]:
gdp1 = pd.Series([2.8, 3.01, 8.99, 8.59, 5.18])
gdp1

0    2.80
1    3.01
2    8.99
3    8.59
4    5.18
dtype: float64

In [3]:
type(gdp1)

pandas.core.series.Series

In [4]:
gdp1.index#默认的索引从0开始，因为一共5个数，所以索引为0-4

RangeIndex(start=0, stop=5, step=1)

In [5]:
gdp1.values

array([2.8 , 3.01, 8.99, 8.59, 5.18])

2.通过字典构建：调用pd.Series()方法

In [6]:
gdp2 = pd.Series({'北京': 2.8, '上海': 3.01, '广东': 8.99, '江苏': 8.59, '浙江': 5.18})
gdp2

北京    2.80
上海    3.01
广东    8.99
江苏    8.59
浙江    5.18
dtype: float64

In [7]:
type(gdp2)

pandas.core.series.Series

In [8]:
gdp2.index#用字典构建series,索引为字典的key

Index(['北京', '上海', '广东', '江苏', '浙江'], dtype='object')

In [9]:
gdp2.values

array([2.8 , 3.01, 8.99, 8.59, 5.18])

3.通过numpy数组构建:调用pd.Series()方法

In [10]:
gdp3 = pd.Series(np.array([2.8, 3.01, 8.99, 8.59, 5.18]))
gdp3

0    2.80
1    3.01
2    8.99
3    8.59
4    5.18
dtype: float64

In [11]:
type(gdp3)

pandas.core.series.Series

In [12]:
gdp3.index#同第一种方法

RangeIndex(start=0, stop=5, step=1)

In [13]:
gdp3.values

array([2.8 , 3.01, 8.99, 8.59, 5.18])

- 索引Series

1.行号索引

In [14]:
#取gdp1中的第1 4 5个元素
gdp1[[0, 3, 4]]

0    2.80
3    8.59
4    5.18
dtype: float64

2.名称索引:针对索引是名称的

In [15]:
#取gdp2的上海，江苏，浙江的值
gdp2[['上海','江苏','浙江']]

上海    3.01
江苏    8.59
浙江    5.18
dtype: float64